#!/bin/sh /etc/rc.common
# Telegraf init script
# Copyright (C) 2017 VCCloud <tienhoangvan@vccorp.vn>
 
START=102
STOP=152
  
USE_PROCD=1

start_service() {
        procd_open_instance
        procd_set_param command /usr/sbin/telegraf --config /etc/telegraf.conf
        procd_set_param stdout 1 # forward stdout of the command to logd
		procd_set_param stderr 1 # same for stderr
        procd_close_instance
}


